travis:
  secure:
    BINSTAR_TOKEN: ER+h5bufrqrVGq6/vGEKaLe0PYOmSAnPVm5SvyjTEE99+bFf+EJ3scxPi0ew1tEnhRqAIACtPtrGz5YWMnqW8X3jrwU3VKo/VbiUUZtBACERHh7QaZMg05e0t8zI+CQ3ValpTdG4UUBdL9HZwKuBXltEWDxz+wjJUat5QDrGsZ7BCxsjhyElEBzbOYrHv8CCAPCyi6TAdWnVRaaUyNnua+q+Hd0a6u8HtnEvnGAYfr9EFGsjmtk/zeb5ehAHgH/QcC+Yyfu/FpqDm5DuQiWl5Ac9dKQSCTcF+1LJmUpJLT6m6TB/5DIWJ+bp9Br1ciFlQVip/xYTWhKxwfYTfwuCOFDlYN8CcHtjfMPw8qm47+AdcVvb1z2+Ac4wfu7H7UF+mSDHswZPvfoy+X1SaGiFoHL3pZBNRqEu8shZUOQ6oWR7t6+a0rkbaaeuangV+gPNXsXgWk/umi0MM7nNHGiuvJKjUZaf3fOKE2qcY2fRDPFzUwspNJ2F9ieT2tdmaSKGJ/uOrNUQIuC1p1JKkYbT1fFtn1e1gVKv8pTi1ke6W5UTTVvhMACA/5e9q6i9X3wAKuk6ieUlEG2N3lKYQSd295XqHgc8jDSbg6mUyARRxp8XXYcF3xgAkO9lKKRI7JjaVMHz5WRsVQGi/gE8oXSz5caunFsmlspZ1Xix8bAHDew=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
